# Generated by Django 5.0.6 on 2024-08-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
