# Generated by Django 5.0.6 on 2024-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
