# Generated by Django 5.0.6 on 2024-08-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quizinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinvite',
            name='branch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='quizinvite',
            name='college',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizinvite',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizinvite',
            name='passyear',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizinvite',
            name='phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
