# Generated by Django 5.0.6 on 2024-08-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quizinvite_branch_quizinvite_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='company',
            field=models.CharField(blank=True, default=False, max_length=50),
        ),
    ]
