# Generated by Django 5.0.6 on 2024-08-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quiz_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='company',
            field=models.CharField(blank=True, default='@LEADCODER', max_length=50),
        ),
    ]
