# Generated by Django 5.0.6 on 2024-08-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_quiz_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
