# Generated by Django 5.0.6 on 2024-09-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_quiz_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.IntegerField(),
        ),
    ]
