# Generated by Django 5.0.6 on 2024-09-12 16:16

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_quiz_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('qid', models.BigAutoField(primary_key=True, serialize=False)),
                ('questions', ckeditor_uploader.fields.RichTextUploadingField()),
                ('marks', models.IntegerField()),
                ('categoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
