# Generated by Django 5.0.6 on 2024-09-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionlevel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='QuestionBank',
        ),
    ]
