# Generated by Django 5.1.1 on 2024-11-13 18:37

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_question_levelofq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSubmit',
            fields=[
                ('prosid', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', ckeditor_uploader.fields.RichTextUploadingField()),
                ('code_input', models.CharField(max_length=100)),
                ('code_output', models.CharField(max_length=100)),
                ('submited_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
