# Generated by Django 5.0.6 on 2024-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_quizManager',
            field=models.BooleanField(default=False),
        ),
    ]
